### PR TITLE
Split rule into ruleparts to prevent long glob patterns (failing unde…

### PR DESCRIPTION
**Pull request by mmodler**
…r windows)

Fix for #1

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm, what about splitting the globs up into an array instead? So instead of `{$docs} {$tests} MoreTests` we get: `[$docs, $tests, 'MoreTests']`

**Comment by mmodler** [comment]
Do you talk about changing the rules format?

**Comment by barryvdh** [comment]
Yes but just to allow both array or a string.

**Comment by mmodler** [comment]
Hm, then i would change everything to array syntax?

**Comment by mmodler** [comment]
OT: Is there a commandline composer command to force plugin execution? This would make testing much more comfortable :)

**Comment by mmodler** [comment]
How to go on with this? I really like to use the plugin ;)

**Comment by barryvdh** [comment]
I meant something like this: https://github.com/barryvdh/composer-cleanup-plugin/commit/3bf4b1b597720f639b7f4f42e2645ea653218a5d

So now we still have the 'fast' glob brace thing, but just split into smaller parts.

Does this work for you?

**Comment by mmodler** [comment]
So i looked over it again: It would be easy to handle rules in array format. But if you look the config file, the combination of default rules and custom rules in array format can only be done with array_merge. Do you think this would be preferable over the string format?

**Comment by barryvdh** [comment]
Not sure, what do you mean? What do you need to merge?

**Comment by mmodler** [comment]
I misunderstood you new config format. As i see it now, i would prefer it because it skips the braced syntax {$var}. So the new config format looks good for me.

**Globbing:**
Its not bullet proof as long as you combine multiple patterns, because the string consists of full path to package + patterns. So it could easily overcome the 260 chars limit:

D:/mydevworkspace/repositories/mycoolproject/vendor/longervender/longercoolpackagename/{ longer set of custom package patterns}

The only secure way is to spilt into single globs, because a single glob pattern would never become longer as the target file url (windows / the os) can handle nativly.

**Comment by mmodler** [comment]
If you agree with me, i can do another pr for array config + single globs if you like?

**Comment by barryvdh** [comment]
Hmm, yeah it could only be max 120 chars or so (still a lot longer then your example), but not sure what the speed impact is. 

But okay, make it single globs, without the brace.

**Comment by mmodler** [comment]
Running composer directly under Win globbing the win filesystem, i can't see any delay. I will do the pr now.

**Comment by mmodler** [comment]
New PR #6

**Pull request closed without merging**
