### PR TITLE
Split patterns for single globs (should be max 260 chars)

### PR DESCRIPTION
**Pull request by mmodler**

### CODE REVIEW

**Comment by barryvdh** [comment]
Instead of the nested foreach, we could also implode(' ', $rules) them again, to make 1 long string.

And we don't need the BRACE option now, right?

**Comment by mmodler** [comment]
If we implode with '' we'll get:

...readme*.travis.yml

if we implode with ' ' we might get empty patterns later and have to check for this.

Do you still like to get rid of the bested foreach? :)

**Comment by barryvdh** [comment]
Neh then leave it like this.

This ready?

**Comment by mmodler** [comment]
Worked for me in my test project

**Comment by barryvdh** [comment]
Thanks

**Pull request merged**
